### PR TITLE
Bionomia: Add kingdom to occurrence download; add identifiers.avro

### PR DESCRIPTION
**Pull request by dshorthouse**
Am assuming here that kingdom is in occurrence here along with family.

### CODE REVIEW

**Comment by MattBlissett** [comment]
Hi,

Could you check if https://www.gbif-uat.org/occurrence/download/0000513-210105134143568 is as you would expect?

**Comment by MattBlissett** [comment]
Or https://www.gbif-uat.org/occurrence/download/0000515-210105134143568 which is smaller (same as above, but only fungi).

**Comment by dshorthouse** [comment]
Perfect! Thanks, @MattBlissett. I checked these in the scripts at my end and they work. That additional avro output included in here helps accelerate processing at my end even more. At the time you made these, I didn't do much of anything with identifiedByID or recordedByID whereas now I do.

**Comment by dshorthouse** [comment]
Any idea when this might be available on production? Trying to coordinate a migration at my end, dependent on this one.

**Comment by MattBlissett** [comment]
It should be available now (actually from yesterday afternoon UTC).

**Pull request merged**
